create table fun_logs (
  id bigint generated by default as identity primary key,
  inserted_at timestamp with time zone default timezone('utc'::text, now()) not null,
  data jsonb
);

alter table fun_logs enable row level security;

CREATE POLICY "Enable read access for all users" ON "public"."fun_logs"
AS PERMISSIVE FOR SELECT
TO public
USING (true)

CREATE POLICY "Enable insert for authenticated users only" ON "public"."fun_logs"
AS PERMISSIVE FOR ALL
TO authenticated, anon, service_role
USING (true)
